### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by StevenZzz07** [paul007pl/ECG#2]
Hi, first thanks for your inspiring work! Point cloud rendering figures in your paper are very beautiful, such as the depth-aware shading. How do you draw it? Using open3d, meshlab or other programmes?

Thanks!
![image](https://user-images.githubusercontent.com/56421441/110420582-86ed7e00-80d6-11eb-97f7-0ecf419f31dd.png)

**Comment by paul007pl** [comment]
I do not remember clearly...

**Comment by paul007pl** [comment]
I do not remember clearly...
Maybe you can try matplotlib.pyplot, or try the code provided by PointNet.
You can also try Open3D and meshlab, but I think they do not support colormap.

**Comment by StevenZzz07** [comment]
Got it! Thank you very much!
