### ISSUE TITLE
A problem about train

### ISSUE THREAD

**Issue by small-beebee** [paul007pl/ECG#5]
Traceback (most recent call last):
  File "/mnt/txf/codes/ECGNet/main.py", line 35, in <module>
    models_dict[args.model_name](args)
  File "/mnt/txf/codes/ECGNet/train/ecg_train.py", line 60, in train
    loss_net.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected isFloatingType(grads[i].type().scalarType()) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

I have tried to solve this problem, but I still haven't solved it. Please help me to solve it, I will be very grateful to you.

**Comment by paul007pl** [comment]
It's hard for me to debug here... But I got 2 suggestions that can be helpful:
1. maybe read thess:
https://discuss.pytorch.org/t/runtimeerror-expected-isfloatingtype-grads-i-scalar-type-to-be-true-but-got-false-could-this-error-message-be-improved/79298/15
https://github.com/pytorch/pytorch/issues/37680
2. maybe try the other repository: VRCNet (it supports ECG also)
Hope that helps.
